### ISSUE TITLE
Getting the project off the ground

### ISSUE THREAD

**Issue by bernardchen** [bernardchen/bike.ai#1]
## TODO:
- [x] Init this repo with necessary files and cleaned up versions of lab skeleton
- [x] SD card logging: https://github.com/lab11/buckler/blob/master/software/apps/sd_card/main.c
- [x] Collect test data for deceleration spikes
- [x] Proximity Sensor proof-of-concept
- [x] Start coding (State machine, structure, abstract away inputs/outputs)

## Ideas for future
- [ ] Use gyroscope / accelerometer rotation angles to determine which axes to measure deceleration on
- [ ] Maybe detect natural deceleration based on the slope (i.e. if we detect downhill, threshold is lower, since any deceleration is likely due to braking. If uphill, threshold is higher)
